name = "libretv-worker"
main = "apps/worker/src/index.ts"
compatibility_date = "2024-11-20"

[vars]
ADMIN_EMAIL = "admin@example.com"
ADMIN_PASSWORD = "changeme"

# Optional: uncomment and bind real resources when created in Dashboard
#[[kv_namespaces]]
#binding = "KV_SESS"
#id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxx"
#
#[[kv_namespaces]]
#binding = "KV_CACHE"
#id = "yyyyyyyyyyyyyyyyyyyyyyyyyyyy"
#
#[[d1_databases]]
#binding = "DB"
#database_name = "libretv"
#database_id = "zzzzzzzz-zzzz-zzzz-zzzz-zzzzzzzzzzzz"
